### PR TITLE
Start the spritesheet as playing, like in original movieclips //patch

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/spritesheet/13)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/13)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/13)*

**Comment by gogoprog** [comment]
*[spritesheet/SpritesheetMovieClip.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/13#-KshGzP73AZgT2r34kg_:-KshGzP73AZgT2r34kga:b-1eyjn) ([raw file](https://github.com/fishingcactus/spritesheet/blob/643aa1910772c6052b99fba19792126579d9300f/spritesheet/SpritesheetMovieClip.hx#L23)):*
>         play ();
>    

I agree it should match the movieclip behavior but then the autoUpdate should also always be set

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/13)*

**Comment by NuclearCookie** [comment]
*[spritesheet/SpritesheetMovieClip.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/13#-KshGzP73AZgT2r34kg_:-KshHhEPoUla8WqeN5vc:b-rvwigj) ([raw file](https://github.com/fishingcactus/spritesheet/blob/643aa1910772c6052b99fba19792126579d9300f/spritesheet/SpritesheetMovieClip.hx#L23)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

>         play ();
>    

I agree it should match the movieclip behavior but then the autoUpdate should also always be set
</blockquote></details>

No, updating is handled by this class, not by AnimatedSprite. Done in a previous merge request.
Setting autoUpdate is now forbidden when using SpritesheetMovieclips

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/13)*

**Pull request merged**
