### PR TITLE
Fixed framescript behavior to be consistent to normal movieclip behavior

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/spritesheet/11)

### CODE REVIEW

**Comment by crazyjul** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[spritesheet/SpritesheetMovieClip.hx, line 38 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/11#-KsOQgJKIJFd2iYLfa3v:-KsOQgJKIJFd2iYLfa3w:b-whys8g) ([raw file](https://github.com/fishingcactus/spritesheet/blob/8ac0574d2861f09247efc2ca8f90d205a5338548/spritesheet/SpritesheetMovieClip.hx#L38)):*
> ```Haxe
>     public override function play() {
>         if ( !clip.autoUpdate ) {
>             clip.autoUpdate = true;
> ```

doesn't that check need to be done inside set_autoUpdate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/11)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/11)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[spritesheet/SpritesheetMovieClip.hx, line 38 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/11#-KsOQgJKIJFd2iYLfa3v:-KsOSxr_U86fH_Gpl0K-:b-tv1tfc) ([raw file](https://github.com/fishingcactus/spritesheet/blob/8ac0574d2861f09247efc2ca8f90d205a5338548/spritesheet/SpritesheetMovieClip.hx#L38)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

doesn't that check need to be done inside set_autoUpdate?
</blockquote></details>

It's a simple field, not a property. I've removed the checks because they are pointless

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/11)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/11#-:-KsOTK8-Tg1jPFkCrq4e:bnfp4nl)*

**Pull request merged**
