### PR TITLE
Rewritten SpritesheetMovieClip frame scripts without using Events

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/spritesheet/8)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[spritesheet/AnimatedSprite.hx, line 270 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Khg-Z46fz6ewRYnso-i:-Khg-Z471Tx4zZGKjsJb:b-gypp9v) ([raw file](https://github.com/fishingcactus/spritesheet/blob/68782d36fcba3e73a2bf7585fdc15529629e9997/spritesheet/AnimatedSprite.hx#L270)):*
> ```Haxe
> 	private function set_currentFrameIndex(index) {
> 		__currentFrameIndex = index;
> 		return __currentFrameIndex;
> ```

combine those 2 lines in on return __cur = index

---

*[spritesheet/SpritesheetMovieClip.hx, line 46 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Khg-iSfKnO4PpPuwBDh:-Khg-iSfKnO4PpPuwBDi:b-dft1k7) ([raw file](https://github.com/fishingcactus/spritesheet/blob/68782d36fcba3e73a2bf7585fdc15529629e9997/spritesheet/SpritesheetMovieClip.hx#L46)):*
> ```Haxe
>     override public function __enterFrame(deltaTime:Int) {
>         var currentFrameIndex = @:privateAccess clip.__currentFrameIndex;
>         
> ```

extra white spaces

---

*[spritesheet/SpritesheetMovieClip.hx, line 47 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Khg-mnfu6DCOxfI8B7H:-Khg-mnfu6DCOxfI8B7I:bmcn340) ([raw file](https://github.com/fishingcactus/spritesheet/blob/68782d36fcba3e73a2bf7585fdc15529629e9997/spritesheet/SpritesheetMovieClip.hx#L47)):*
> ```Haxe
>         var currentFrameIndex = @:privateAccess clip.__currentFrameIndex;
>         
>         if(currentFrameIndex != lastFrameIndex) {
> ```

You need to execute all scripts between last and current frame index

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by gogoprog** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[spritesheet/AnimatedSprite.hx, line 270 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Khg-Z46fz6ewRYnso-i:-KhgH0Wsr6PvFWqLHftt:b-896fix) ([raw file](https://github.com/fishingcactus/spritesheet/blob/68782d36fcba3e73a2bf7585fdc15529629e9997/spritesheet/AnimatedSprite.hx#L270)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

combine those 2 lines in on return __cur = index
</blockquote></details>

Done.

---

*[spritesheet/SpritesheetMovieClip.hx, line 46 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Khg-iSfKnO4PpPuwBDh:-KhgH1DLUbaW-L7Axom1:b-896fix) ([raw file](https://github.com/fishingcactus/spritesheet/blob/68782d36fcba3e73a2bf7585fdc15529629e9997/spritesheet/SpritesheetMovieClip.hx#L46)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

extra white spaces
</blockquote></details>

Done.

---

*[spritesheet/SpritesheetMovieClip.hx, line 47 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Khg-mnfu6DCOxfI8B7H:-KhgH1pVz-4YR8stdcUm:b-896fix) ([raw file](https://github.com/fishingcactus/spritesheet/blob/68782d36fcba3e73a2bf7585fdc15529629e9997/spritesheet/SpritesheetMovieClip.hx#L47)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

You need to execute all scripts between last and current frame index
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[spritesheet/SpritesheetMovieClip.hx, line 48 at r2](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Ki4fsZ91StnscKm2BAF:-Ki4fsZ91StnscKm2BAG:bed1zc7) ([raw file](https://github.com/fishingcactus/spritesheet/blob/0ed22bfbfc388877e8f633c90f39384c5b8bd9ae/spritesheet/SpritesheetMovieClip.hx#L48)):*
> ```Haxe
> 
>         if(currentFrameIndex != lastFrameIndex) {
>             if (__frameScripts != null) {
> ```

Missing support for static framescripts. I would prefer to re-use the existing code for this. Can't we refactor the base class to make it possible?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by gogoprog** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[spritesheet/SpritesheetMovieClip.hx, line 48 at r2](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-Ki4fsZ91StnscKm2BAF:-KiEa1JoFMUzJHrSngiu:bjef4up) ([raw file](https://github.com/fishingcactus/spritesheet/blob/0ed22bfbfc388877e8f633c90f39384c5b8bd9ae/spritesheet/SpritesheetMovieClip.hx#L48)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Missing support for static framescripts. I would prefer to re-use the existing code for this. Can't we refactor the base class to make it possible?
</blockquote></details>

I just updated the code.
I tried to refactor but it implied too many changes : refactor format.MovieClip, refactor display.MovieClip, adding new parameters.. etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/8#-:-KiU2IZyoMV_Of5tIXIR:bnfp4nl)*

**Pull request merged**
