### PR TITLE
Added fake movieclip

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/spritesheet/7)

### CODE REVIEW

**Comment by gogoprog** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[spritesheet/FakeMovieClip.hx, line 3 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-Kf7WnRqNbQFg-BlWN8B:-Kf7WnRqNbQFg-BlWN8C:b-kox2bw) ([raw file](https://github.com/fishingcactus/spritesheet/blob/e8f7d547f994808f4e15e20096a4d0d6b71b2533/spritesheet/FakeMovieClip.hx#L3)):*
> ```Haxe
> package spritesheet;
> 
> class FakeMovieClip extends AnimatedSprite {
> ```

Shouldnt this class extend MovieClip and override its methods? (to allow cast(clip, MovieClip)) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[spritesheet/FakeMovieClip.hx, line 3 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-Kf7WnRqNbQFg-BlWN8B:-Kf7bAGD85YX-okJfHVF:b-5r1h76) ([raw file](https://github.com/fishingcactus/spritesheet/blob/e8f7d547f994808f4e15e20096a4d0d6b71b2533/spritesheet/FakeMovieClip.hx#L3)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Shouldnt this class extend MovieClip and override its methods? (to allow cast(clip, MovieClip)) ?
</blockquote></details>

hmm no. I just want the same interface, but not all the complexity of those classes.. this works in most cases. and I believe an unsafe cast might work here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[spritesheet/FakeMovieClip.hx, line 3 at r1](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-Kf7WnRqNbQFg-BlWN8B:-KfBejo_5aS_w1c4P-_A:b-55hgpf) ([raw file](https://github.com/fishingcactus/spritesheet/blob/e8f7d547f994808f4e15e20096a4d0d6b71b2533/spritesheet/FakeMovieClip.hx#L3)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

hmm no. I just want the same interface, but not all the complexity of those classes.. this works in most cases. and I believe an unsafe cast might work here
</blockquote></details>

OK since you changed it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-:-KfBf3Oq_4bx8DpQDKtD:bnfp4nl)*

**Comment by crazyjul** [comment]
I'll accept this MR as releases are dependent on it, but I would like the design to be adapted

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[spritesheet/AnimatedSprite.hx, line 272 at r3](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-KfGgTNuPu4WKgC2Ccyu:-KfGgTNvJuElJf9JUXxt:bkjjg) ([raw file](https://github.com/fishingcactus/spritesheet/blob/c440e31b78459c58b423c5dedd6c10df3241d50b/spritesheet/AnimatedSprite.hx#L272)):*
> ```Haxe
> 	private function set_currentFrameIndex(index) {
> 		__currentFrameIndex = index;
> 		dispatchEvent(new Event(UPDATE_CURRENT_FRAME));
> ```

This whole system seems really expensive. I would rather execute this from the movie clip class. 

---

*[spritesheet/SpritesheetMovieClip.hx, line 69 at r3](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-KfGg8Bpaz-koFWaJaeA:-KfGg8Bpaz-koFWaJaeB:b-rhizxn) ([raw file](https://github.com/fishingcactus/spritesheet/blob/c440e31b78459c58b423c5dedd6c10df3241d50b/spritesheet/SpritesheetMovieClip.hx#L69)):*
> ```Haxe
>         // Don't change the behavior. just advance frames.
>         if (Std.is (frame, Int)) {
> 			ratio = cast(frame, Float) / (clip.currentBehavior.frames.length-1);
> ```

I'm not sure about this, as timeline might be made of several behavior. But I'll accept it as it is

---

*[spritesheet/SpritesheetMovieClip.hx, line 81 at r3](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-KfGgbiMqGPtT10jIL-H:-KfGgbiMqGPtT10jIL-I:brg3dl8) ([raw file](https://github.com/fishingcactus/spritesheet/blob/c440e31b78459c58b423c5dedd6c10df3241d50b/spritesheet/SpritesheetMovieClip.hx#L81)):*
> ```Haxe
>             var index = @:privateAccess clip.__currentFrameIndex;
>             if (__frameScripts.exists (index)) {
>                 __frameScripts.get (index) ();
> ```

Behavior might not start from frame 0, and a timeline might be made of several behavior. I believe there's some lookup table missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7#-:-KfGgoV4sXjqWeMpE1nP:bmfmr2d)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/spritesheet/7)*

**Pull request merged**
